name: Update-Count-In-File.txt
on:
  push:
    branches: 
      - main

jobs:
  Update-Commit-Count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone repo
        run: |
          git clone https://${{ secrets.AWS_GITHUB_USER }}:${{ secrets.AWS_GITHUB_TOKEN }}@github.com/rishitha1007/Update-count
          # git checkout uat
          cd Update-count
          ls
          git branch

      - name: Update Count
        run: |
          
          cd Update-count
          ls
          #!/bin/bash
          count=$(($(grep -oP '(?<=My commit count is: )\d+' text-file.txt)+50))
          sed -i "s/My commit count is: \d\+/My commit count is: $count/" text-file.txt
          
      - name: Commit And Push
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@wohlig.com"
          git add .
          git commit -m "Updating Count"
          git push
      
      
