name: Update-Count-In-File.txt
on:
  push:
    branches: 
      - main

jobs:
  Update-Commit-Count:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone repo
        run: |
          git clone https://${{ secrets.AWS_GITHUB_USER }}:${{ secrets.AWS_GITHUB_TOKEN }}@github.com/rishitha1007/Update-count
          git checkout uat

      - name: Update Count
        run: |
          #!/bin/bash
          COUNT=$(awk '/My commit count is:/{print $5}' file.txt)
          UPDATED_COUNT=$((COUNT + 50))
          awk -v count="$UPDATED_COUNT" '/My commit count is:/{$5=count"."} 1' file.txt > temp.txt && mv temp.txt file.txt
      
      - name: Commit And Push
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@wohlig.com"
          git add updateCount.txt
          git commit -m "Updating Count"
          git push
      
      
